
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      # Build the project
      - name: Build project
        run: ./bin/junit/monprojet/build.sh  # Commande pour exécuter le script de build
        working-directory: src/junit/monprojet  # Répertoire de travail pour le build

      # Run unit tests using JUnit
      - name: Run unit tests
        run: ./bin/junit/monprojet/run_tests.sh  # Commande pour exécuter les tests
        working-directory: src/junit/monprojet  # Répertoire de travail pour les tests

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Déploiement de l'application dans un environnement de production
      - name: Deploy to production
        run: |
          # Commandes pour déployer votre application dans un environnement de production
          # Par exemple, copier les fichiers sur un serveur
          cp -r src/junit/monprojet /path/to/production/directory
        working-directory: src/junit/monprojet  # Répertoire de travail pour le déploiement
